### ISSUE TITLE
Doens't compile with base-4.7 (GHC-7.8)

### ISSUE THREAD

**Issue by phadej** [brendanhay/gogol#32]
```
src/Network/Google/Types.hs:318:34:
    Not in scope: ‘foldMap’
    Perhaps you meant one of these:
      ‘CL.foldMap’ (imported from Data.Conduit.List),
      ‘ifoldMap’ (imported from Control.Lens),
      ‘CL.foldMapM’ (imported from Data.Conduit.List)
```

made bound revisions on Hackage
