### ISSUE TITLE
Gogol fails to compile with GHC 9.6

### ISSUE THREAD

**Issue by m4dc4p** [brendanhay/gogol#191]
I'm looking ahead and trying to compile gogol with 9.6. The `gogol` component fails to compile due to missing instances:

```
src/Gogol/Auth/ApplicationDefault.hs:172:12: error: [GHC-39999]
    • No instance for ‘Alternative (Either String)’
        arising from a use of ‘<|>’
    • In the expression: x <|> y
      In a case alternative: _ -> x <|> y
      In a stmt of a 'do' block:
        case (x, y) of
          (Left xe, Left ye)
            -> Left
                 $ "Failed parsing service_account: "
                     ++ xe ++ ", Failed parsing authorized_user: " ++ ye
          _ -> x <|> y
    |
172 |     _ -> x <|> y
    |            ^^^
```

It's an easy fix, see #190.

I'm not sure about other components as I'm just fixing these as they come up in my codebase, but if they have similar errors the fix should be as easy.

**Comment by danwdart** [comment]
Should this be closed since the PR has been?
